# Generated by Django 5.0.6 on 2024-06-03 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dekan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_nome', models.CharField(max_length=200)),
                ('fan_soat', models.IntegerField()),
                ('fan_kredit', models.CharField(blank=True, help_text='F.I.SH', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('familya', models.CharField(max_length=250)),
                ('ota', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Grops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uqov_yil', models.DateField()),
                ('smester', models.CharField(choices=[('1', '1-semester'), ('2', '2-semester'), ('3', '3-semester'), ('4', '4-semester'), ('5', '5-semester'), ('6', '6-semester'), ('7', '7-semester'), ('8', '8-semester'), ('9', '9-semester'), ('10', '10-semester')], default='1', max_length=8)),
                ('name', models.CharField(max_length=200)),
                ('fan', models.ManyToManyField(to='pdfupload.fan')),
                ('teachers', models.ManyToManyField(to='pdfupload.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='KafidraMudir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uqitovchi_ism', models.CharField(help_text='I.F.O', max_length=250)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.fakultet')),
            ],
        ),
        migrations.AddField(
            model_name='fan',
            name='kafidra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.kafidramudir'),
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('familya', models.CharField(max_length=250)),
                ('ota', models.CharField(max_length=250)),
                ('talaba_id', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.grops')),
            ],
        ),
        migrations.CreateModel(
            name='Talababaholash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField()),
                ('bahosi', models.IntegerField(blank=True)),
                ('uquv_boshqarma_boshligi', models.CharField(help_text='F.I.SH', max_length=200)),
                ('or_nazorat_masul', models.CharField(help_text='F.I.SH', max_length=150)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.fan')),
                ('grups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.grops')),
                ('kafidra_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.kafidramudir')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.talaba')),
            ],
        ),
        migrations.AddField(
            model_name='fan',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.teachers'),
        ),
        migrations.CreateModel(
            name='Yunalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.fakultet')),
            ],
        ),
        migrations.AddField(
            model_name='talaba',
            name='yunalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.yunalish'),
        ),
        migrations.AddField(
            model_name='kafidramudir',
            name='yunalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.yunalish'),
        ),
        migrations.AddField(
            model_name='grops',
            name='yunalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.yunalish'),
        ),
    ]
