# Generated by Django 5.0.6 on 2024-06-03 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uqov_yil', models.CharField(max_length=25)),
                ('yunalish', models.CharField(choices=[('AMALIY_M_F', 'Amaliy matematika va fizika'), ('2', "Boshlang'ich ta'lim va gumaniter fanlar funkuteti"), ('3', 'Tabiy fanlar fakulteri'), ('SANATSHUNOSLIK_FAKULTETE', "Sanatshunoslik fakul'teti"), ('JISMONIY_MADANIYAT_SPORT_VA_MK_TALIM', "Jismoniy madaniyat, sport va Maktabgacha ta'lim fakulteti"), ('FILOLOGIYA_FAKULTETI', 'filologiya fakulteti')], max_length=60, verbose_name="yo'nalish")),
                ('smester', models.CharField(choices=[('TEXNOLOGIYA_T_Y', 'TEXNOLOGIYA talim kafidrasi'), ('RUS_TILI_ADABIYOT_K', 'Rus tili va adabiyoti kafedrasi'), ('MATEMATIKA_VA_INFORMATIKA', 'Matematika va Informatika'), ('MAKTABGACHA_TALIM_K', " Maktabgacha ta'lim kafidrasi"), ('UZBEK_TILI_VA_ADABIYOTI_K', "o'zbek tili va adabiyoti kafedrasi"), ('BOSHLANGICH_TALIM_K', "Boshlang'ich talim nazariyasi kafedrasi"), ('PEDAGOGIKA_K', 'Pedagogika kafedrasi'), ('BOSHLANGICH_TALIM_METODIKASI_K', "Boshlang'ich talim metodikasi kafedrasi"), ('PSIXOLOGIYA_K', 'Psixologiya kafedrasi'), ('XORIJIY_TILLAR_K', 'Xorijiy tillar kafedrasi'), ('TASVIRIY_SANAT_VAmUHANDISLIK_K', "Tasviriy san'at va muhandislik grafikasi kafidrasi"), ('MUSIQA_TALIM_K', "Musiqa ta'lim kafedrasi"), ('SPORT_TURLARINI_UQITISH_METO_K', "Sport turlarini o'qitish metodikasi kafedrasi"), ('KIMYO_K', 'Kimyo kafedrasi'), ('FIZIKA_ASTRONOMIYA_K', 'Fizika astronomiya kafedrasi'), ('JISMONIY_MADANIYAT_NAZARIYASI_VA_MATEMATIKASI_K', 'Jismoniy madaniyat nazariyasi va m,k'), ('BIOLOGIYA_VA_GEOGRAFIYA_K', 'Biologiya va Geografiya kafedrasi'), ('IJTIMOIY_GUMANITAR_FANLAR_K', 'Ijtimoiy gumanitar fanlar Kafedrasi')], max_length=60)),
                ('fan_nomi', models.CharField(max_length=200)),
                ('gruh_nomi', models.CharField(max_length=200)),
                ('fan_soat', models.IntegerField()),
                ('fan_kredit', models.CharField(blank=True, help_text='F.I.SH', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('familya', models.CharField(max_length=250)),
                ('ota', models.CharField(max_length=250)),
                ('talaba_id', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.grops')),
            ],
        ),
        migrations.CreateModel(
            name='Talababaholash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField()),
                ('bahosi', models.IntegerField(blank=True)),
                ('uquv_boshqarma_boshligi', models.CharField(help_text='F.I.SH', max_length=200)),
                ('oraliq_nazorat_masul', models.CharField(help_text='F.I.SH', max_length=150)),
                ('kafedra_mudiri', models.CharField(max_length=50)),
                ('grups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.grops')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.talaba')),
            ],
        ),
    ]
